kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - cron

steps:
  - name: install
    image: node:16-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:16-alpine
    commands:
      - yarn command lint:check

  - name: build
    image: node:16-alpine
    commands:
      - yarn command build

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/node-fnm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: update-readme
    image: cenk1cenk2/pipe-update-docker-hub-readme
    settings:
      repo: cenk1cenk2/node-fnm
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      readme_repository: cenk1cenk2/node-fnm
      readme_file: ./README.md
      readme_description: |
        Monorepo aimed Node development container that hosts FNM in a container.

  - name: inform
    image: drillster/drone-email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from:
        from_secret: smtp_username
    when:
      status:
        - changed
        - failure

image_pull_secrets:
  - dockerconfigjson
