kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - cron

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    commands:
      - yarn command lint:check

  - name: build
    image: node:current-alpine
    commands:
      - yarn command build

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/node-fnm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: update readme
    image: cenk1cenk2/pipe-update-docker-hub-readme
    settings:
      repo: cenk1cenk2/node-fnm
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      readme_repository: cenk1cenk2/node-fnm
      readme_file: ./README.md
      readme_description: |
        A monorepo aimed node.js development container that hosts fnm (Fast Node Manager) in a container to install with any node version.
      debug: 1

image_pull_secrets:
  - dockerconfigjson
