kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - cron

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    commands:
      - yarn command lint:check

  - name: build
    image: node:current-alpine
    commands:
      - yarn command build

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/node-fnm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

image_pull_secrets:
  - dockerconfigjson
