kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - push
    - cron

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    depends_on:
      - install
    commands:
      - yarn command lint:check

  - name: build
    image: node:current-alpine
    depends_on:
      - install
    commands:
      - yarn command build

  - name: semantic-release
    depends_on:
      - build
    image: cenk1cenk2/drone-semantic-release
    settings:
      semantic_release: false
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      docker_repo: cenk1cenk2/node-fnm

  - name: publish-buildx
    image: docker:dind
    depends_on:
      - semantic-release
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker version
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - apk add curl --no-cache --no-progress
      - mkdir -p ~/.docker/cli-plugins
      - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - docker buildx create --use --name builder
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 $DOCKER_IMAGE_TAG --push .
    environment:
      BUILDX_VERSION: v0.5.1
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_IMAGE_TAG: -t cenk1cenk2/node-fnm:latest

services:
  - name: docker
    image: docker:dind
    privileged: true
    command:
      - --experimental
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

image_pull_secrets:
  - dockerconfigjson
