stages:
  - install
  - build
  - publish
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/node-fnm
  README_DESCRIPTION: |
    Monorepo aimed Node development container that hosts FNM in a container.

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

build:
  variables:
    NODE_BUILD_CWD: ./supervisor
  artifacts:
    paths:
      - supervisor/dist/
      - supervisor/oclif.manifest.json

.publish-docker-to-public:
  stage: publish
  trigger:
    include:
      - project: devops/pipes
        file: /templates/docker-build-with-artifacts-dockerhub.gitlab-ci.yml
    strategy: depend

publish-node-fnm-latest:
  extends: .publish-docker-to-public
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKERFILE_NAME: Dockerfile
    IMAGE_TAGS: latest
  only:
    refs:
      - master
      - tags

publish-node-fnm-edge:
  extends: .publish-docker-to-public
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKERFILE_NAME: Dockerfile-edge
    IMAGE_TAGS: edge
  only:
    refs:
      - master
      - tags
