stages:
  - install
  - build
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/node-fnm
  NODE_PACKAGE_MANAGER: pnpm
  NODE_LINT_COMMAND: lint

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/update-docker-hub-readme.gitlab-ci.yml

build:
  artifacts:
    paths:
      - supervisor/dist/
      - supervisor/oclif.manifest.json

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  dependencies:
    - build
  parallel:
    matrix:
      - DOCKERFILE_NAME: Dockerfile
        DOCKER_IMAGE_TAGS: latest-${GITLAB_CI_ARCH}
        DOCKER_MANIFEST_TARGET: latest
        DOCKER_IMAGE_BUILD_ARGS: S6_OVERLAY_ARCH={{- if eq $.GITLAB_CI_ARCH "amd64" }}amd64{{- else if eq $.GITLAB_CI_ARCH "arm64" }}aarch64{{- end }}
        GITLAB_CI_ARCH:
          - amd64
          - arm64
  only:
    refs:
      - schedules
      - master

docker-manifest:
  stage: post
  extends: .docker-manifest-dockerhub
  dependencies:
    - docker-build
  only:
    refs:
      - schedules
      - master

update-docker-hub-readme:
  stage: post
  extends: .update-docker-hub-readme
  dependencies:
    - build
  variables:
    README_DESCRIPTION: |
      Monorepo aimed Node development container that hosts FNM in a container.
  only:
    refs:
      - schedules
      - master
