stages:
  - install
  - build
  - publish
  - post

variables: {}

include:
  - project: devops/pipes
    file: /templates/node-build.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml
    ref: main

.publish-docker-to-public:
  stage: publish
  trigger:
    include:
      - project: devops/pipes
        file: /templates/docker-build-with-artifacts-dockerhub.gitlab-ci.yml
        ref: main
    strategy: depend

build:
  variables:
    NODE_BUILD_CWD: ./supervisor
  artifacts:
    paths:
      - supervisor/dist/

publish-node-fnm-latest:
  extends: .publish-docker-to-public
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKERFILE_NAME: Dockerfile
    IMAGE_NAME: cenk1cenk2/node-fnm
    IMAGE_TAGS: latest
    NODE_BUILD_CWD: ./supervisor
  only:
    refs:
      - master
      - tags

publish-node-fnm-edge:
  extends: .publish-docker-to-public
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKERFILE_NAME: Dockerfile-edge
    IMAGE_NAME: cenk1cenk2/node-fnm
    IMAGE_TAGS: edge
  only:
    refs:
      - master
      - tags

update-docker-hub-readme:
  variables:
    README_REPOSITORY: cenk1cenk2/node-fnm
    README_FILE: ./README.md
    README_DESCRIPTION: |
      Monorepo aimed Node development container that hosts FNM in a container.
