stages:
  - install
  - build
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/node-fnm

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/update-docker-hub-readme.gitlab-ci.yml

build:
  variables:
    NODE_BUILD_CWD: ./supervisor
  artifacts:
    paths:
      - supervisor/dist/
      - supervisor/oclif.manifest.json

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  parallel:
    matrix:
      - DOCKERFILE_NAME: Dockerfile-${GITLAB_CI_ARCH}
        DOCKER_IMAGE_TAGS: latest-${GITLAB_CI_ARCH}
        DOCKER_MANIFEST_TARGET: latest
        GITLAB_CI_ARCH:
          - amd64
          - arm64
  only:
    refs:
      - schedules
      - master

docker-manifest:
  stage: post
  extends: .docker-manifest-dockerhub
  only:
    refs:
      - schedules
      - master

update-docker-hub-readme:
  stage: post
  extends: .update-docker-hub-readme
  variables:
    README_DESCRIPTION: |
      Monorepo aimed Node development container that hosts FNM in a container.
  only:
    refs:
      - schedules
      - master
