#!/bin/bash

PACKAGE_FOLDER=packages

#!/bin/bash

source <(curl -s "https://gist.githubusercontent.com/cenk1cenk2/0446f3be22a39c9f5fe5ee1cfb3cca63/raw/cli.sh?$(date +%s)")

print_header

export PACKAGE_FOLDER=packages

run_cli ${*:1}
