version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:test
    build:
      context: .
    environment:
      LOG_LEVEL: debug
      SERVICE_0_CWD: supervisor
    volumes:
      - .:/data/app
