version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        S6_OVERLAY_ARCH: amd64
    environment:
      LOG_LEVEL: trace
      PACKAGE_MANAGER: pnpm
      DEFAULTS_LOGS: 'true'
      DEFAULTS_COMMAND: pnpm run dev:start
      SERVICE_0_CWD: supervisor
    volumes:
      - .:/data
