package_manager: PACKAGE_MANAGER
dont_install:
  __name: DONT_INSTALL
  __format: json
force_install:
  __name: FORCE_INSTALL
  __format: json
before_all:
  __name: BEFORE_ALL
  __format: json

defaults:
  node_version: NODE_VERSION
  sync_wait:
    __name: SYNC_WAIT
    __format: json
  restart_wait:
    __name: RESTART_WAIT
    __format: json
  enable: DEFAULTS_ENABLE
  before:
    __name: DEFAULTS_BEFORE
    __format: json
  log:
    stdout:
      __name: DEFAULTS_LOG_STDOUT
    stderr:
      __name: DEFAULTS_LOG_STDERR
    lifetime:
      __name: DEFAULTS_LOG_LIFETIME
  command: DEFAULTS_COMMAND
  sync:
    __name: DEFAULTS_SYNC
    __format: json
  exit_on_error:
    __name: DEFAULTS_EXIT_ON_ERROR
    __format: json
  run_once:
    __name: DEFAULTS_RUN_ONCE
    __format: json
  environment:
    __name: DEFAULTS_ENVIRONMENT
    __format: json

services:
  __name: SERVICES
  __format: json
  __element:
    name: SERVICE_${i}_NAME
    cwd: SERVICE_${i}_CWD
    enable:
      __name: SERVICE_${i}_ENABLE
      __format: json
    before:
      __name: SERVICE_${i}_BEFORE
      __format: json
    log:
      stdout:
        __name: SERVICE_${i}_LOG_STDOUT
      stderr:
        __name: SERVICE_${i}_LOG_STDERR
      lifetime:
        __name: SERVICE_${i}_LOG_LIFETIME
    command: SERVICE_${i}_COMMAND
    sync:
      __name: SERVICE_${i}_SYNC
      __format: json
    exit_on_error:
      __name: SERVICE_${i}_EXIT_ON_ERROR
      __format: json
    environment:
      __name: SERVICE_${i}_ENVIRONMENT
      __format: json
    node_version: SERVICE_${i}_NODE_VERSION
    sync_wait:
      __name: SERVICE_${i}_SYNC_WAIT
      __format: json
    restart_wait:
      __name: SERVICE_${i}_RESTART_WAIT
      __format: json
