# global settings
package_manager: pnpm # valid values npm, yarn
dont_install: false # disables the initial install process where node_modules is not found
force_install: false # to add --force flag to the package manager for initial start
before_all: false # runs something before running anything else, can be an array of command or false

# default settings will be injected to all the services
defaults:
  node_version: default # set the node version, overwrites the nvmrc file in the root. version that can fnm or nvm can accept
  sync_wait: 10 # wait between the services a pre-given time if sync is true
  restart_wait: 3 # wait before restarting the service, if crashed
  enable: true # enables or disables a service
  before: false # a command to run before the task, can be an array of commands or false
  log: # logs can be an enum of 0, fatal, error, warn, info, debug, trace
    stdout: info
    stderr: warn
    lifetime: debug
  load_dotenv: true # if the flag is set, this will load the .env file in the service.cwd
  command: pnpm run dev:start # default command to run
  sync: false # this will run the sync flagged services first and one-by-one with the sync_wait and run the others afterwards
  run_once: false # run the service once and do not try to restart
  exit_on_error: true # exit the whole container when there is a error with a given service
  # Object for passing in environment variables to services
  # environment:

# definition of the services, will overwrite the defaults for each service
# you can use the same settings in the defaults here as well
services:
  - cwd: . # current working directory relative to /data
    # name: # you can give a friendly name to the service, if empty it will use the cwd
    # command: pnpm run dev:start
