node_version: NODE_VERSION
package_manager: PACKAGE_MANAGER
dont_install:
  __name: DONT_INSTALL
  __format: json
force_install:
  __name: FORCE_INSTALL
  __format: json
sync_wait:
  __name: SYNC_WAIT
  __format: json
restart_wait:
  __name: RESTART_WAIT
  __format: json
check_directories:
  __name: CHECK_DIRECTORIES
  __format: json
before_all:
  __name: BEFORE_ALL
  __format: json

defaults:
  enable: DEFAULTS_ENABLE
  before:
    __name: DEFAULTS_BEFORE
    __format: json
  logs: DEFAULTS_LOGS
  load_dotenv:
    __name: DEFAULTS_LOAD_DOTENV
    __format: json
  command: DEFAULTS_COMMAND
  sync:
    __name: DEFAULTS_SYNC
    __format: json
  exit_on_error:
    __name: DEFAULTS_EXIT_ON_ERROR
    __format: json
  run_once:
    __name: DEFAULTS_RUN_ONCE
    __format: json
  environment:
    __name: DEFAULTS_ENVIRONMENT
    __format: json

services:
  __name: SERVICES
  __format: json
