/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HttpsGitlabKilicDevDockerVizierPipeVizierConfig = VizierConfig

export interface VizierConfig {
  steps: VizierStep[]
}
export interface VizierStep {
  name?: string
  commands?: VizierStepCommand[]
  permissions?: VizierStepPermission[]
  templates?: VizierStepTemplate[]
  shouldDisable?: string | boolean
  delay?: string
  background?: boolean
  parallel?: boolean
  log?: VizierStepLogLevel
}
export interface VizierStepCommand {
  name?: string
  cwd?: string
  command: string
  script?: VizierStepCommandScript
  retry?: VizierStepCommandRetry
  environment?: {
    [k: string]: string
  }
  runAs?: VizierStepCommandRunAs
  health?: VizierStepCommandHealth
  shouldDisable?: string | boolean
  parallel?: boolean
  delay?: string
  background?: boolean
  log?: VizierStepCommandLogLevel
  pipe?: VizierStepCommandPipe
}
export interface VizierStepCommandScript {
  inline?: string
  file?: string
  ctx?: unknown
}
export interface VizierStepCommandRetry {
  retries?: number
  always?: boolean
  delay?: string
}
export interface VizierStepCommandRunAs {
  user: string
  group?: string
}
export interface VizierStepCommandHealth {
  ensureIsAlive?: boolean
  ignoreError?: boolean
}
export interface VizierStepCommandLogLevel {
  stdout?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  stderr?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  lifetime?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  permissions?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  delay?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  background?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
}
export interface VizierStepCommandPipe {
  stdin?: boolean
}
export interface VizierStepPermission {
  path: string
  chown?: VizierChown
  chmod?: VizierChmod
  recursive?: boolean
  shouldDisable?: string | boolean
  parallel?: boolean
  log?: VizierStepPermissionLogLevel
}
export interface VizierChown {
  user: string
  group?: string
}
export interface VizierChmod {
  file?: string
  dir?: string
}
export interface VizierStepPermissionLogLevel {
  chown?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  chmod?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
}
export interface VizierStepTemplate {
  inline?: string
  input?: string
  output: string
  ctx?: unknown
  chmod?: VizierChmod
  chown?: VizierChown
  shouldDisable?: string | boolean
  parallel?: boolean
  log?: VizierStepTemplateLogLevel
}
export interface VizierStepTemplateLogLevel {
  generation?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  ctx?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  chown?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  chmod?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
}
export interface VizierStepLogLevel {
  delay?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
  background?: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace'
}
